### ISSUE TITLE
Understanding the RF FE

### ISSUE THREAD

**Issue by 0y8w1x** [will127534/LoRa-GW-FeatherWing#6]

**Comment by will127534** [comment]
You might want to take a look at SX1302 datasheet: [https://www.semtech.com/products/wireless-rf/lora-core/sx1302](https://www.semtech.com/products/wireless-rf/lora-core/sx1302) for the first half of your question.

The additional SX1262 is for Listen-Before-Talk Feature, basically act as channel activity scanning.
